# 9
inspecode:
  experimental:
    cache: true
    dependencies:
      tools:
        gem:
          cache: true
          failure-check: true
    incremental: true

  thresholds:
    complexity: 15

  rubocop:
    thresholds:
      num-issues: 0
